datamade/how-to

README.md
aws/rds.md

This PR adds documentation for how to set up an EC2 instance to communicate with an RDS instance.
Connects https://gitlab.com/ChicagoDataCooperative/court-terminal/issues/15.

Add docs for communicating between EC2 and RDS

---

README.md
ux/README.md
ux/project-research-and-interviews.md

Add a new folder for UX knowledge, and initialize it with the [Project Research and Interviews doc](https://docs.google.com/document/d/1NgmcCfBE3B9bTYF2TyTSY5m4QA6xLu2DxESeUTQYxUo/edit?usp=sharing).
Closes #14.
- View the Markdown preview of the new README: https://github.com/datamade/how-to/blob/feature/jfc/project-research-and-interviews/README.md
- View the preview of the new UX folder: https://github.com/datamade/how-to/tree/feature/jfc/project-research-and-interviews/ux
- View the preview of the new doc: https://github.com/datamade/how-to/blob/feature/jfc/project-research-and-interviews/ux/project-research-and-interviews.md

Initialize UX folder with doc for Project Research and Interviews

---

project-management/README.md
project-management/naming-things.md

This PR moves EvZ's docs for naming things from https://github.com/datamade/deploy-a-site/pull/49 to this repo. Now that we're collecting docs for project management in this repo, I figured it was a better place for these docs to live.
These changes had already been approved in https://github.com/datamade/deploy-a-site/pull/49. I called out the portions that I edited for clarity, which you may want to re-review.
* View the rendered markdown on GitHub
* Confirm new links work
* Confirm text looks good

Migrate docs for naming project artifacts

---

README.md
django/README.md
django/django-cms.md
django/django-compressor.md
django/django-rest-framework.md

This PR adds a directory for Django and begins a table enumerating our preferred plugins for common use cases. It also adds stub documentation for `django-compressor` and `django-compressor-toolkit`. 
Related to #22.

Add Django toolkit

---

.github/PULL_REQUEST_TEMPLATE.md

This PR swaps "Closes" with "Handles" in the PR template. I made this change because we want issues to remain open for filing in our project board. We close them manually once a month.
- View the rendered markdown on GitHub and confirm that it looks good and I spelled my one-word substitution correctly. ;-)

Change closes to handles in PR template

---

README.md
environment-setup.md

See description.
In addition to adding Docker, I did some finessing of the language in our environment setup and also added GatsbyJS to the section on static sites.
I also made the editorial decision to alphabetize the contents in the README to make things easier to find.
Handles https://github.com/datamade/ops/issues/634.
* View the rendered [README.md](https://github.com/datamade/how-to/blob/hec/onboarding-revision/README.md) and [environment-setup.md](https://github.com/datamade/how-to/blob/hec/onboarding-revision/environment-setup.md) files, and confirm the markdown looks nice.
* Click links and confirm they resolve.
* Suggest any changes (please and thank you)!

Migrate and revise environment setup, update README index

---

README.md
ci/README.md
ci/github-actions.md
ci/research/recommendation-of-adoption.md

This PR adds a recommendation of adoption for GitHub Actions, as well as some initial documentation for the service.
Connects #36. 
* View the Markdown preview of the recommendation of adoption and Actions docs and confirm they look good
* Test new links and confirm that they work
* Confirm I haven't missed any `Contents` links in any READMEs

Add docs and recommendation of adoption for GitHub Actions

---

docker/templates/python/{{cookiecutter.directory_name}}/docker-compose.yml

GitHub Actions [always requires `POSTGRES_PASSWORD` be set](https://github.community/t5/GitHub-Actions/Services-name-resolution-error/m-p/37397/highlight/true#M2924) in order to run a Postgres service. This isn't necessarily well-documented, but it tripped me up and was difficult to debug, so I think we should consider always setting `POSTGRES_PASSWORD` in the config file here.
* Not really sure if this needs detailed testing. I tested it in https://github.com/datamade/mn-election-archive/ and it worked well.

Always set POSTGRES_PASSWORD in docker-compose.yml

---

docker/local-development.md

This PR adds a section on `.env` files to the documentation for local development with Docker. I included some reasons I like this approach in general. Here are some reasons I prefer this approach to Blackbox:
- GPG is tough to set up and use. Defining variables in a file and excluding that file from version control is not.
- We no longer use encrypted secrets in deployment settings, and we've broadly adopted LastPass as an alternative means of secrets management. It seems only natural to remove it from the equation for local development.
* Click the top navigation links and the external links in the new copy and confirm they resolve correctly.

Add guidance on managing secrets for local development

---

README.md
heroku/README.md
heroku/scheduling-tasks.md

Add some documentation for scheduling tasks on Heroku.
Connects #76.
While this PR recommends Cron To Go, there are actually a couple of different Heroku services that offer similar scheduling functionality, notably [Advanced Scheduler](https://elements.heroku.com/addons/advanced-scheduler) and [Temporize](https://elements.heroku.com/addons/temporize). I tried all three and Cron To Go was the clear winner in terms of pricing, number of features, and ease of use of the dashboard. It felt like overkill to me to write a recommendation of adoption for this decision, but if you think it's necessary as part of this PR I'd be happy to add it on.
* View the rendered markdown and confirm it looks good
* Test links and make sure they resolve

Add documentation for scheduling tasks on Heroku

---

django/README.md
django/django-compressor.md
django/django-react-integration.md
docker/templates/new-django-app/{{cookiecutter.app_name}}/package.json
docker/templates/new-django-app/{{cookiecutter.app_name}}/requirements.txt
docker/templates/new-django-app/{{cookiecutter.app_name}}/{{cookiecutter.module_name}}/settings.py

This PR adds documentation and updates the `new-django-app` template to recommend a pattern for using React components in a Django app.
Connects #66.
* View the rendered markdown, confirm it looks good and links resolve properly
* Change to the `docker/templates` directory and create a new app with `docker-compose run --rm cookiecutter -f new-django-app`
* Accept all default Cookiecutter options
* Change to the `my-new-app` repo and build container images with `docker-compose build`
* Follow the instructions in the `Usage` section of the new docs and use the example code to test the hybrid integration
* Visit http://localhost:8000 and confirm you see the text `Welcome, foobar!` below
* Once you're done testing, remember to clean up the testing app:
* `docker-compose down --volumes`
* `cd …

Add docs and update templates for Django-React integration

---

logging/slack.md

Sentry's new Slack app changes the interface for configuring Slack integrations. This PR updates our docs to match that change.
* View the rendered markdown and confirm it looks good
* Navigate to the Settings dashboard in Sentry and confirm that the instructions accurately describe the interface

Update Sentry-Slack docs to match new integration

---

docker/templates/new-django-app/{{cookiecutter.app_name}}/docker-compose.yml
docker/templates/python-docker-env/{{cookiecutter.directory_name}}/docker-compose.yml

I don't fully understand why we set app containers to automatically restart in development, and it has the annoying side effect of causing random apps to start up when I start up Docker. This PR proposes removing this setting from the `new-django-app` and `python-docker-env` environments.
* Confirm the change is reasonable

Don't automatically restart app containers

---

docker/templates/new-django-app/{{cookiecutter.app_name}}/Dockerfile
docker/templates/new-django-app/{{cookiecutter.app_name}}/{{cookiecutter.module_name}}/settings.py

Update the `Dockerfile` and `settings.py` files in the `new-django-app` template to properly install GDAL and set the Django engine to support PostGIS as a backend when `postgis` is `True`.
Handles #93.
* Change into the `docker/templates/` directory
* Run `docker-compose run --rm cookiecutter -f new-django-app`
* Accept all default settings, but set `postgis` to `True`
* Change into `my-new-app/` and run `docker-compose up --build`
* Confirm that the app builds properly and is visible on http://localhost:8000
* Shut down the app with `docker-compose down --volumes`
* Change back to the `docker/templates/` directory and remove the new app with `rm -RF my-new-app`
* Remove old image with `docker rmi my-new-app`
* Create a new app **without** PostGIS support by running `docker-compose run …

Fix PostGIS support in new-django-app template

---

README.md
django/README.md
django/translation.md

This PR adds some initial docs representing our current best practices for translating Django apps.
Handles #90.
* View the rendered markdown
* Confirm links resolve properly
* Confirm that the text looks good and is typo-free

Add docs for Django translations

---

investment-time/README.md
investment-time/research.md

This PR adds the proposal, pilot, recommendation, and documentation of investment time at DataMade.
Handles https://github.com/datamade/hr/issues/26 (internal link)
* Click the links and confirm they resolve correctly.

Add investment time documentation

---

postgres/Streaming-replication.md

Co-authored-by: Jean Cochrane <jeancochrane@users.noreply.github.com>
This PR migrates still-relevant documentation from devops to this repo.
Handles #119 
The documentation that has not been migrated concerns our legacy deployment (specifically, CloudWatch and Logrotate). I chose not to move that over, but let me know if you think that's wrong.
* View the rendered markdown and confirm it looks good, and that the links resolve. (I updated the link to interacting with a remote database to point to the docs in this repo -- make sure I didn't miss others!)

Migrate @jeancochrane's guide to streaming replication

---

docker/templates/new-django-app/{{cookiecutter.app_name}}/{{cookiecutter.module_name}}/settings.py

See title. This change is necessary because tests otherwise fail when hitting routes that return templates containing compressed JavaScript. See: https://github.com/datamade/california-dream-index/pull/49
* Repeat the testing instructions from https://github.com/datamade/how-to/pull/84.

Specify NODE_PATH so locally installed packages can be found

---

heroku/deploy-a-django-app.md

After going through the [Heroku setup process for Erikson EDI](https://github.com/datamade/erikson-edi/pull/162/), I documented a number of additional steps that tripped me up.
Handles #129 
* Confirm that the instructions are clear and unambiguous. 
* Check that hyperlinks work

Updated instructions for heroku setup for legacy apps

---

project-management/collateral.md

This PR adds an overview of how to approach research to the project collateral documentation.
Related to https://github.com/datamade/hr/issues/30
Artifacts for topical research are a new thing, so I'll want to announce that more broadly once this comes in.
* View the rendered markdown and confirm it looks good and the links resolve.

Add research to project collateral docs

---

docker/templates/new-gatsby-app/{{cookiecutter.app_name}}/gatsby-config.js
docker/templates/new-gatsby-app/{{cookiecutter.app_name}}/package.json
docker/templates/new-gatsby-app/{{cookiecutter.app_name}}/yarn.lock
gatsby/README.md
gatsby/recharts.md
logging/sentry.md

The PR adds documentation for using Sentry and Recharts in Gatsby.
Closes #127. 
Closes #72.
* Read through the new pages and edit for clarity, completeness, and working links.
* I considered adding Sentry to the Gatsby template instead, but it felt wrong to install it as a dependency before a project has a DSN string. Check that assumption for me.

Gatsby plugin docs (Sentry & Recharts)

---

etl/airflow.md

This PR adds documentation to capture our team knowledge and best practices for Airflow.
Co-authored by @jeancochrane and @fatima3558!
Handles #88
* View the rendered Markdown and confirm that it looks good, and that the links resolve.
* Review the copy and ensure that it is clear and consistent.

Add first draft of Airflow documentation

---

ci/README.md
ci/github-actions.md
ci/research/amendment-1.md
ci/research/recommendation-of-adoption.md

This PR adds a recommendation of adoption for a third-party CodeDeploy integration for GitHub Actions. It also updates our GitHub Actions to cover this use case. It does _not_ add a cookiecutter for this pattern, as we don't maintain one for PyPI, another deployment edge case.
Handles #36.
* View the rendered markdown and confirm it looks good, and that the links resolve.
* Review the prose and confirm it is clear and makes sense.

Add recommendation of adoption for GH Actions / CodeDeploy

---

docker/local-development.md

Closes #176.
- View the branch `fix-broken-links` for this repo in Github.
- Visit `~/docker/local-development.md`
- Test the links in the `Components` heading. Numbers 1, 2, and 3 have links to the cookie cutter template. Those links should take you to the correct place.

Fixed broken links in /docker/local-development.md

---

docker/templates/new-django-app/{{cookiecutter.app_name}}/README.md
docker/templates/new-django-app/{{cookiecutter.app_name}}/babel.config.json
docker/templates/new-django-app/{{cookiecutter.app_name}}/package.json
docker/templates/new-django-app/{{cookiecutter.app_name}}/{{cookiecutter.module_name}}/settings.py

See title. These changes are necessary so our Django/React integration emits JavaScript code that's compatible with both modern and legacy browsers.
Handles #149 
* Review the prose and confirm it is clear and helpful.
* Follow the instructions to create a new Django app from our `new-django-app` Docker template.
* `cd` into your new app directory and build the app: `docker-compose build app`
* Follow the instructions in the app README to identify and transpile third-party plugins that may contain ES6 code. 
* Run your app and visit the homepage. View the page source, find the link to the compiled JavaScript, and open it in your and confirm it contains transpiled plug-in code.

Add default Babel config and documentation to identify and transpile potentially problematic Node plugins

---

ci/github-actions.md

Updates our example `main.yml` for GitHub Actions to include a line for copying over `.env.example` to `.env`. From my experience, this is now our standard practice.

github-actions: adds .env config step to main.yml

---

postgres/Interacting-with-a-remote-database.md

The domain for `opencivicdata.org` has expired and now redirects to a potentially malicious site:
Unless someone in the Open Civic Data community purchases the domain from the new owner, we will need to update all `opencivicdata.org` links to point to https://opencivicdata.readthedocs.io/en/latest/
The following links are impacted:
* docs.opencivicdata.org
* api.opencivicdata.org
* opencivicdata.org
This PR updates the link in our postgres documentation to point to readthedocs.

updates expired link to opencivicdata.org

---

mapping/README.md
mapping/leaflet.md
mapping/react-leaflet.md
mapping/svg-maps.md

This PR adds mapping documentation, written by Fatima and Sam. It closes issue #184.
For the `react-leaflet` section, we didn't have many open source examples to point to. So I tried to write a guide based on some patterns I found while learning and working with `react-leaflet`, combined with my knowledge of React. Please go through that section with a highly critical mind.
There's also some key information included in that section that isn't included in the official `react-leaflet` docs. 
- Read documentation and suggest any edits/needs for clarification/confusing sentences/etc.
- Go through the tutorial in the react-leaflet section.
- Add any notes or information that we might be overlooking.

add fatima and sam's mapping documentation

---

docker/templates/new-django-app/{{cookiecutter.app_name}}/README.md

Adds some documentation on making a github image public.

public setting/authentication for github docker images

---

docker/templates/new-django-app/{{cookiecutter.app_name}}/docker-compose.yml

This adds some commented out code to the docker-compose.yml file for using a container registry image.
closes #252

instructions for using container registry image in local development

---

docker/templates/new-django-app/{{cookiecutter.app_name}}/.github/workflows/publish_docker_image.yml

Fixes a cookiecutter issue with new GH action for docker registry.
- Recreate the bug:
- pull down main
- create a new django app from the template and see error
- Fix:
- pull down `add-raw` branch
- create a new django app from the template
- make sure your `~/publish_docker_image.yml` looks like [it does on the main branch](https://github.com/datamade/how-to/blob/main/docker/templates/new-django-app/%7B%7Bcookiecutter.app_name%7D%7D/.github/workflows/publish_docker_image.yml)

add raw tags to github action expressions

---

ci/github-actions.md

This PR adds a bit about setting up Google Lighthouse CI to the ci/github-actions part of our how-to documentation
Connects #245

add github-actions section on lighthouse ci config

---

README.md
mapping/accessibility.md
mapping/leaflet.md

This adds documentation on leaflet's built in accessibility and general tips for mapping a11y.
Closes #222, closes #328 
* Read through to make sure that everything makes sense.

Document leaflet and general mapping a11y

---

docker/templates/new-django-app/cookiecutter.json
docker/templates/new-django-app/{{cookiecutter.app_name}}/Dockerfile
docker/templates/new-wagtail-app/cookiecutter.json
docker/templates/new-wagtail-app/{{ cookiecutter.app_name }}/Dockerfile

See title.
Handles #346 
* Create cookiecutter Django and Wagtail projects
* Verify that `docker-compose build` runs without error

Update Node install script in Cookiecutter Dockerfiles

---

docker/templates/new-django-app/{{cookiecutter.app_name}}/.gitignore
docker/templates/new-django-app/{{cookiecutter.app_name}}/Dockerfile
docker/templates/new-django-app/{{cookiecutter.app_name}}/Dockerfile.dev
docker/templates/new-django-app/{{cookiecutter.app_name}}/docker-compose.yml
docker/templates/new-django-app/{{cookiecutter.app_name}}/package.json
docker/templates/new-django-app/{{cookiecutter.app_name}}/requirements.txt
docker/templates/new-django-app/{{cookiecutter.app_name}}/webpack.config.js
docker/templates/new-django-app/{{cookiecutter.app_name}}/{{cookiecutter.module_name}}/settings.py
docker/templates/new-django-app/{{cookiecutter.app_name}}/{{cookiecutter.module_name}}/templates/{{cookiecutter.module_name}}/index.html

This PR replaces Django compressor with Webpack in the Django cookiecutter template. We'll make this change for the Wagtail template via issue #318.
- closes #291
- clone this branch and follow cookiecutter steps to create a new django app
- test that the cookiecutter javascript code works

replace django compressor with webpack in the django cookiecutter template

---

work-practices/version-control/source-control.md

This PR removes references to legacy services and updates our pattern for branches and deployment.
* Review the rendered MarkDown and confirm that it is formatted correctly, and the prose makes sense.

Make minor updates to version control documentation
