datamade/how-to

README.md
moving-keys-between-servers.md

Tutorial on moving keys between servers

---

CODE_OF_CONDUCT.md
README.md

Add the DataMade Anti-Harassment Policy as a `CODE_OF_CONDUCT.md` to this repo.
Closes #13.
- View the Markdown preview of the new README: https://github.com/datamade/how-to/blob/feature/jfc/code-of-conduct/README.md
- View the Markdown preview of the new CoC: https://github.com/datamade/how-to/blob/feature/jfc/code-of-conduct/CODE_OF_CONDUCT.md

Add anti-harassment policy as CODE_OF_CONDUCT.md

---

docker/README.md
docker/local-development.md
docker/research/comparisons-to-existing-tools.md
docker/research/recommendation-of-adoption.md

Add artifacts for proposed pilot of containerized environments for local development, including:
- Benefits of Docker
- Comparison to existing tools
- Documentation of approach from private proof of concept
Closes #16.

Add artifacts for local development with Docker

---

docker/local-development.md

This PR removes a redundant installation of Python from our example Dockerfile.
Related to #41.
N/A
N/A
* View the rendered markdown in GitHub, and ensure it looks good.

Remove unnecessary Python installation from example Dockerfile

---

docker/local-development.md

This PR adds links to Docker documentation of core concepts, plus a brief explanation of image and container life cycle and a strategy for resetting your development environment.
Closes #43. 
* View the rendered Markdown on GitHub.
* Ensure that formatting looks good and prose is legible.

Expand Docker documentation

---

ux/README.md
ux/project-research-and-interviews.md

Add in link to user research report template.
- Please review the link and add comments with suggestions, corrections, or clarifications.

Add in link to user research report template

---

django/forms.md

Initialize a document for collecting best practices for working with Django forms.
Closes #3.
* View the rich markdown preview of `django/forms.md`
* Confirm the text and formatting look good

Initialize recommendations for Django forms

---

gatsby/README.md
gatsby/stack.md

See title. I wrote this for developers who, like me, have little or no exposure to JavaScript package management.
* View the rendered markup and confirm it looks good.
* Check that the links resolve correctly.

Add brief overview of development stack for Gatsby applications

---

environment-setup.md

This PR adds a couple of sentences about how to safely transfer data into a replacement computer, and how to wipe the old computer clean. Includes links to Apple documentation.
- Make sure the new information is complete and that the links go to the right place.

Add info for computer replacement

---

docker/local-development.md

See title. Handles #107.
* View the rendered markdown and confirm it looks good, and that the links resolve.
* Pick a containerized project and clone one of the third-party dependencies to your machine.
* Follow the instructions to install it into your application container.
* Make a simple change to your local copy of the dependency (e.g., add a `print()` statement to a section of the code that's evaluated, or raise a phony exception). Trigger the code that you changed, and confirm that the change is reflected during execution.

Add docs for local development of packages

---

logging/sentry.md

See title.
Handles https://github.com/datamade/devops/issues/110, closes #124.
* View the rendered markdown and confirm that it looks good and links resolve.
* Review the new prose and confirm it makes sense.

Update Sentry docs with notes on raven, bookkeeping

---

CONTRIBUTING.md

See title. Edits are outlined in https://github.com/datamade/how-to/issues/98#issuecomment-705769575.
Handles #98.
* Review the prose and confirm it's clear and accurately reflects our current R&D practice.

Update CONTRIBUTING.md to reflect current practice

---

heroku/deploy-a-django-app.md

See title.
Closes #118 and closes #94.
* Check the diff and make sure it looks good
* Test setting up a new Heroku pipeline for an existing app following the instructions and make sure our commands all succeed

Add docs for Heroku CLI for review apps and Heroku database disruption emails

---

gatsby/README.md

This PR adds my top tips for Gatsby debugging to this repo. Originally I'd opened this issue for React debugging, but after doing some reading I think it makes sense to focus this specifically on Gatsby projects. If you see other categories I'm missing, or tactics that work for you, please let me know @hancush!
Closes #114. 
* Read over the new section and check it for clarity and completeness
* Make sure all the links work!

Add tips for Gatsby debugging

---

docker/templates/new-gatsby-app/{{cookiecutter.app_name}}/.github/PULL_REQUEST_TEMPLATE
docker/templates/new-gatsby-app/{{cookiecutter.app_name}}/README.md

This PR makes the changes to the Gatsby cookiecutter template described in #140.
@fatima3558 I'd love your review on this once you've had a chance to look at https://github.com/sunrisedatadept/green-jobs/pull/4

Gatsby template fixes from first use

---

docker/templates/README.md
docker/templates/new-django-app/{{cookiecutter.app_name}}/.gitignore
docker/templates/new-gatsby-app/{{cookiecutter.app_name}}/README.md
docker/templates/python-docker-env/cookiecutter.json

See commit messages.
* Follow the instructions to create a Docker environment for an existing app. `rsync` it to an empty directory and confirm all files are moved to the right location. 
* The Gatsby update is just a documentation fix, so no testing required there.
* The new Django app change does not represent a material change in behavior, so I don't think it needs to be tested.

Patch bugs in all three Docker templates

---

work-practices/project-management/README.md
work-practices/project-management/delegation.md
work-practices/ux/README.md

See title.
Handles #133
* Confirm the prose makes sense.
* Confirm the links resolve, especially the external links to Google Docs.

Add documentation on delegation

---

heroku/deploy-a-django-app.md

This PR is for #161. I've made changes to the Heroku deployment instructions, based on the discussions in that issue.
- edited the Heroku CLI steps
- reorganized Heroku config info
- added a troubleshooting section
Please don't hesitate to edit for clarity. Also, scrutinize my terminology. I'm still not 100% certain about the distinction between "apps" and "pipelines".
The diff doesn't show how/where I moved the configuration steps, but they were moved into the "Set up application code for Heroku" section.
- Make sure the heading links still work and point to the correct place, because I changed one and moved another.
- Make sure the new link in the troubleshooting section works.
- Make sure it makes sense.
- Make sure it fits the style and tone.
- Make sure it's helpful.

edited the heroku section

---

ci/github-actions.md

See title.
Connects #166, connects #173
* Review the changes and confirm I haven't introduced any YAML syntax errors. :-)

Add notes on Ubuntu version, GDAL to legacy CI template

---

gatsby/README.md
gatsby/best-practices.md

This PR puts together some of the more salient points from Wes Bos's "Master Gatsby" course and provides additional resources for his recommended implementation.
Handles #158 
* Read through `~/gatsby/best-practices.md` and make any suggestions for clarity, organization, or elaboration
* Double check that `~/gatsby/README.md` table of contents properly links to the `best-practices.md` sections

first draft gatsby best practices from wes bos course

---

README.md
work-practices/README.md
work-practices/external-meetings/README.md

Adds External meetings section to work practies
Handles #180 
Waiting on a Calendly team to be created for Hannah & Derek

adds documentation for calendly

---

django/recaptcha.md

This is for issue #181.
This is based on the steps I took to implement this for Parserator. 
- Use our Django cookiecutter to create a new app and implement recaptcha with a basic form.
- Read for typos, bad/awkward/clunky sentences, and clarity.
- Let me know if there are ways to improve the structure/organization or writing.

Added guide on recaptcha implementation

---

deployment/heroku/deploy-a-django-app.md

This PR adds guidance on setting configuration variables for Heroku review apps.
Closes #211.
Let me know if this needs any clarity.

Add review app config info

---

deployment/heroku/deploy-a-django-app.md

adds section on adding manual ssl cert for heroku
Handles #232

manual ssl certs for heroku

---

deployment/heroku/deploy-a-django-app.md

See title.
Handles #199
[I added this step to the site launch check list a year ago.](https://github.com/datamade/site-launch-checklist/pull/6) 🙈
* Click the new nav link and confirm it goes to the appropriate heading.
* Click the docs links and confirm they go to the right place.

Add step to upgrade production resources in Heroku before launch

---

README.md
python/README.md

See title.
Handles #162
* View the rendered markdown and confirm prose is clear and markup looks good. 
* Click links and confirm they go to the advertised location.
* If you dare, try following the tutorial to generate basic docs for a real or test project.

Add Sphinx/autodoc docs, connects #162

---

deployment/aws/README.md
deployment/aws/iam-s3.md

- For #275, but doesn't close it because we need to script this process
- Review Google doc and edit for clarity
- Go through the steps outlined in the doc and add any missing information, flag any bad information, point out any confusing information, etc
- Add any suggestions for naming IAM and S3 conventions
- Review IAM policy and make sure it's accessing S3 the way we want it

Add doc for s3 access

---

docker/templates/new-django-app/{{cookiecutter.app_name}}/.eslintrc.js
docker/templates/new-django-app/{{cookiecutter.app_name}}/.flake8
docker/templates/new-django-app/{{cookiecutter.app_name}}/.pre-commit-config.yaml
docker/templates/new-django-app/{{cookiecutter.app_name}}/.prettierrc.json
docker/templates/new-django-app/{{cookiecutter.app_name}}/README.md
docker/templates/new-django-app/{{cookiecutter.app_name}}/{{cookiecutter.module_name}}/settings.py

See title.
Handles #247 
* Create a sample project
* Initialize git with `git init`
* Follow pre-commit install instructions (located in README)
* Make your initial commit
* Verify that the new Django project builds and runs as expected

Add pre-commit config to Django cookiecutter

---

scraping/github-actions/recommendation-of-adoption.md

This PR includes a document recommending github actions for ongoing scraping.
will close #212

recommendation for adoption of github actions for scraping

---

accessibility/README.md

This PR adds some information on WCAG 2.1 and VPATs with some resources to learn more on each.
* Read through to confirm that everything makes sense.
* If there's anything I should expand on please let me know!

Add more accessibility info and resources

---

bootstrap/README.md

Adding a short markdown file about our Bootstrap best practices, along with some cool underutilized features I found while reading through the docs.
Handles #XXX
* Read through the `bootstrap/README.md` for typos & let me know if you have any suggestions for additional info to add

add bootstrap overview markdown

---

django/wagtail/README.md

- for #299 
- read language and make sure it makes sense
- make sure link to the section works

add documentation about wagtail cache

---

docker/README.md
docker/tips-n-tricks.md

- closes #269 
Also includes other useful docker commands not mentioned in that issue.

add some docker commands

---

README.md
django/serializing-data.md

- closes #345
Read for clarity and let me know if something doesn't make sense. Also feel free to add DataMade code examples or blog posts related to this topic.

Add doc about serializing with DRF outside of DRF

---

docker/templates/new-django-app/{{cookiecutter.app_name}}/.github/PULL_REQUEST_TEMPLATE.md
docker/templates/new-wagtail-app/{{ cookiecutter.app_name }}/.github/PULL_REQUEST_TEMPLATE.md

See title.
I also added the following language to [the project plan template](https://docs.google.com/document/d/1jsUIZcXiC7UaodTazSEUJjNqaDCHfRMWRgfQVtYNtV8/edit):
> Also consider: Does this project need tests? We prefer to test important core behavior, rather than writing unit tests. If you are creating a website, will it behave differently given certain input data and/or real world conditions, like time of day? Does your ETL pipeline perform complicated transformations on input data? Your project might benefit from testing.
* Confirm there are no other templates that need notes on testing.

Add testing action item to PR template
